[bindings.go.custom_types.BigUint]
imports = ["math/big"]
type_name = "big.Int"
into_custom = """
    n := new(big.Int)
    n, ok := n.SetString({}, 10)
    if !ok {
        panic("invalid big int")
    }
    return *n
"""
from_custom = "{}.String()"

[bindings.go.custom_types.BigDecimal]
imports = ["math/big"]
type_name = "big.Decimal"
into_custom = """
    n := new(big.Decimal)
    n, ok := n.SetString({}, 10)
    if !ok {
        panic("invalid big decimal")
    }
    return *n
"""
from_custom = "{}.String()"
